const booksData = [
  {
    week: '042620',
    headline: 'Sarum',
    citation: 'Edward Rutherford',
    link: 'https://amzn.to/35IEs2d',
    img:
      'https://images.unsplash.com/photo-1503624277759-70b9549d70f6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '050320',
    headline: 'The Count of Monte Cristo',
    citation: 'Alexander Dumas',
    link: 'https://amzn.to/2zm1OyA',
    img: 'https://live.staticflickr.com/7157/6783272731_acd0134d44_b.jpg',
  },
  {
    week: '051020',
    headline: 'Shogun',
    citation: 'James Clavell',
    link: 'https://amzn.to/2L7NyvZ',
    img:
      'https://images.unsplash.com/photo-1583684977172-528983104c31?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '051720',
    headline: 'Becoming',
    citation: 'Michelle Obama',
    link: 'https://amzn.to/2z674GO',
    img: 'https://localist-images.azureedge.net/photos/798916/huge/0087a6c7ef7a577a2bfec91ccf93468631e1d959.jpg',
  },
  {
    week: '052420',
    headline: 'The Choice',
    citation: 'Dr. Edith Eger',
    link: 'https://amzn.to/2ApwX4H',
    img:
      'https://s3-ap-southeast-2.amazonaws.com/ceo-news/wordpress/wp-content/uploads/2020/05/19073453/dr_edith_eger_the_choice.jpg',
  },
  {
    week: '053120',
    headline: 'Cloud Atlas',
    citation: 'David Mitchell',
    link: 'https://amzn.to/2TS6HqF',
    img: 'https://live.staticflickr.com/8285/7695231550_6bb301b258_z.jpg',
  },
  {
    week: '060720',
    headline: 'White Fragility',
    citation: 'Robin DiAngelo',
    link: 'https://amzn.to/3eY5upR',
    img:
      'https://img.apmcdn.org/fadc6810ccb845c54c3a9c154fc0473ddd7c4e34/normal/39fce8-20180705-diangelo-whitefragility-2-collage.jpg',
  },
  {
    week: '061420',
    headline: 'Where the Crawdads Sing',
    citation: 'Delia Owens',
    link: 'https://amzn.to/37iLSKs',
    img:
      'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2018%2F09%2Fdelia-owens-1-2000.jpg&q=85',
  },
  {
    week: '062120',
    headline: 'Upheaval',
    citation: 'Jared Diamond',
    link: 'https://amzn.to/3frbEis',
    img:
      'https://www.rainydaybooks.com/sites/rainydaybooks.com/files/styles/large/public/author_photo/Jared%20Diamond%20Photo%20%26%20Softcover%20Current%2002042020.jpg?itok=NSf2RYRV',
  },
  {
    week: '062820',
    headline: 'Circe',
    citation: 'Madeline Miller',
    link: 'https://amzn.to/2N5rAuJ',
    img: 'https://www.jcpl.org/wp-content/uploads/2018/09/Circe-Blog-1-1024x683.png',
  },
  {
    week: '070520',
    headline: 'Breath',
    citation: 'James Nestor',
    link: 'https://amzn.to/3fKFj6H',
    img: 'https://www.milibrary.org/sites/default/files/events/listing_images/1589576304/Breath.png',
  },
  {
    week: '071220',
    headline: 'The Court of Miracles',
    citation: 'Kester Grant',
    link: 'https://amzn.to/3hF24dG',
    img: 'https://s22421.pcdn.co/wp-content/uploads/2020/03/Untitled-design-40.png',
  },
  {
    week: '071920',
    headline: 'Educated',
    citation: 'Tara Westover',
    link: 'https://amzn.to/2Y85kXu',
    img: 'https://i0.wp.com/www.nationalreview.com/wp-content/uploads/2020/02/tara-westover-educated-book.jpg',
  },
  {
    week: '072620',
    headline: 'Deacon King Kong',
    citation: 'James McBride',
    link: 'https://amzn.to/3i0YtXM',
    img: 'https://www.barnesandnoble.com/blog/barnesy/wp-content/nas-uploads/2020/02/JamesMcBride-575x362.jpg',
  },
  {
    week: '080220',
    headline: 'The Beauty in Breaking',
    citation: 'Michele Harper',
    link: 'https://amzn.to/2WNdcfP',
    img: 'https://crowdcast-prod.imgix.net/-M4sZpXXs-SezOFKNd4A/event-cover-8610?w=800',
  },
  {
    week: '080920',
    headline: 'Tiny Habits',
    citation: 'Dr. BJ Fogg',
    link: 'https://amzn.to/2Dkc24t',
    img: 'https://www.rogerdooley.com/wp-content/uploads/2019/12/bj-fogg_feat.jpg',
  },
  {
    week: '081620',
    headline: 'Caste: The Origins of Our Discontents',
    citation: 'Isabel Wilkerson',
    link: 'https://amzn.to/3imFndZ',
    img:
      'https://hazlitt.net/sites/default/files/styles/article-header-image/public/field/image/wilkerson-main.jpg?itok=gjN-G9tR',
  },
  {
    week: '082320',
    headline: 'Intimations',
    citation: 'Zadie Smith',
    link: 'https://amzn.to/3aPBmw6',
    img: 'https://static.standard.co.uk/s3fs-public/thumbnails/image/2020/07/30/09/zadie-smith-six-essays-main.jpg',
  },
  {
    week: '083020',
    headline: 'A Burning',
    citation: 'Megha Majumdar',
    link: 'https://amzn.to/3hIRYrU',
    img:
      'https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/MUDBJKFPAUI6VB2YX7I5ARKSLI.jpg&w=1200',
  },
  {
    week: '090620',
    headline: 'Surviving Autocracy',
    citation: 'Masha Gessen',
    link: 'https://amzn.to/3lzNPc7',
    img: 'https://www.thenation.com/wp-content/uploads/2020/06/gessen-autocracy-diptych-680x430.jpg',
  },
  {
    week: '091320',
    headline: 'Parakeet',
    citation: 'Marie-Helene Bertino',
    link: 'https://amzn.to/3jtzUCF',
    img:
      'https://i2.wp.com/www.paperbackparis.com/wp-content/uploads/2020/04/Marie-Helene-Bertino-Parakeet-Book-Review.png?fit=1100%2C733',
  },
  {
    week: '092020',
    headline: 'Clean Hands',
    citation: 'Patrick Hoffman',
    link: 'https://amzn.to/3jqhC5hcd',
    img: 'https://orion-uploads.openroadmedia.com/lg_b156ac505a84-patrickhoffman_interview.jpg',
  },
  {
    week: '092720',
    headline: 'The Water Dancer',
    citation: 'Ta-Nehisi Coates',
    link: 'https://amzn.to/3mVPqKg',
    img: 'https://i.ytimg.com/vi/jlm9E7PxHe4/maxresdefault.jpg',
  },
  {
    week: '100420',
    headline: 'How Much of These Hills Is Gold',
    citation: 'C Pam Zhang',
    link: 'https://amzn.to/2HeOQa8',
    img: 'https://rsvpa.witf.org/wp-content/uploads/2020/03/Untitled-6.jpg',
  },
  {
    week: '101120',
    headline: 'The Cold Millions',
    citation: 'Jess Walter',
    link: 'https://amzn.to/3nWDM1X',
    img: 'https://www.publishersweekly.com/images/data/ARTICLE_PHOTO/photo/000/073/73518-1.JPG',
  },
  {
    week: '101820',
    headline: 'Leave the World Behind',
    citation: 'Rumaan Alam',
    link: 'https://amzn.to/3dxIvCt',
    img: 'https://static.onecms.io/wp-content/uploads/sites/6/2020/09/17/Rumaan-Alam.jpg',
  },
  {
    week: '102520',
    headline: 'The Invisible Life of Addie LaRue',
    citation: 'V. E. Schwab',
    link: 'https://amzn.to/35sp0I0',
    img: 'https://www.josephbeth.com/sites/josephbeth.com/files/97B00F45-31F8-4690-974C-FD9702C0F911.JPG',
  },
  {
    week: '110120',
    headline: 'The Evening and the Morning',
    citation: 'Ken Follett',
    link: 'https://amzn.to/34qkkmw',
    img: 'https://s3.amazonaws.com/production.mediajoint.prx.org/public/piece_images/693426/kenfolletpic_small.JPG',
  },
  {
    week: '110820',
    headline: 'Untamed',
    citation: 'Glennon Doyle',
    link: 'https://amzn.to/3juE3pq',
    img: 'https://www.bookpassage.com/sites/bookpassage.com/files/author_photo/doyleGlennon_cover.png',
  },
  {
    week: '111520',
    headline: 'Caste',
    citation: 'Isabel Wilkerson',
    link: 'https://amzn.to/3jwrDNQ',
    img:
      'https://images.csmonitor.com/csm/2020/08/1107113_1_0817-caste-qa-wilkerson_standard.jpg?alias=standard_900x600',
  },
  {
    week: '112220',
    headline: 'Is this Anything',
    citation: 'Jerry Seinfeld',
    link: 'https://amzn.to/3myJplN',
    img: 'https://www.juf.org/uploadedImages/News/Arts_and_Entertainment/SCREENS_Seinfeld.jpg',
  },
  {
    week: '112920',
    headline: 'War',
    citation: 'Margaret MacMillan',
    link: 'https://www.amazon.com/War-How-Conflict-Shaped-Us/dp/1984856138',
    img:
      'https://i.cbc.ca/1.5695710.1598039893!/fileImage/httpImage/image.png_gen/derivatives/16x9_940/war-how-conflict-shaped-us-by-margaret-macmillan.png',
  },
  {
    week: '120620',
    headline: 'Uncanny Valley',
    citation: 'Anna Wiener',
    link: 'https://www.amazon.com/Uncanny-Valley-Memoir-Anna-Wiener/dp/0374278016',
    img: 'https://www.theparisreview.org/blog/wp-content/uploads/2020/01/untitled-6.jpg',
  },
  {
    week: '121320',
    headline: 'A Promised Land',
    citation: 'Barack Obama',
    link: 'https://www.amazon.com/Promised-Land-Barack-Obama/dp/1524763160',
    img: 'https://i.dailymail.co.uk/1s/2020/09/17/13/33299164-0-image-a-12_1600345409022.jpg',
  },
  {
    week: '122020',
    headline: "A Children's Bible",
    citation: 'Lydia Millet',
    link: 'https://www.amazon.com/Childrens-Bible-Novel-Lydia-Millet/dp/1324005033',
    img:
      'https://hips.hearstapps.com/amv-prod-alt.s3.amazonaws.com/wp-content/uploads/2020/05/ATA040420altaask_img01.jpg',
  },
  {
    week: '122720',
    headline: 'Shakespeare in a Divided America',
    citation: 'James Shapiro',
    link: 'https://www.amazon.com/Shakespeare-Divided-America-Plays-Future/dp/0525522298',
    img: 'https://thoughtgallery.org/wp-content/uploads/2020/05/Untitled-design13.jpg',
  },
  {
    week: '010321',
    headline: 'Hidden Valley Road',
    citation: 'Robert Kolker',
    link: 'https://www.amazon.com/Hidden-Valley-Road-Inside-American/dp/038554376X',
    img: 'https://hazlitt.net/sites/default/files/field/image/kolker-main.jpg',
  },
];
