let songsData = [
  {
    week: '042620',
    headline: 'What a Wonderful World',
    citation: 'Louis Armstrong',
    link: 'https://www.youtube.com/watch?v=A3yCcXgbKrE',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Louis_Armstrong_%281955%29.jpg',
  },
  {
    week: '050320',
    headline: 'Afternoons & Coffeespoons',
    citation: 'Crash Test Dummies',
    link: 'https://www.youtube.com/watch?v=W0YeGv5xHUU',
    img: 'https://upload.wikimedia.org/wikipedia/en/8/86/Crash_Test_Dummies_-_God_Shuffled_His_Feet.jpg',
  },
  {
    week: '051020',
    headline: 'It was a Sin',
    citation: 'The Revivalists',
    link: 'https://www.youtube.com/watch?v=ieE4WR4ZrPA',
    img: 'https://images-na.ssl-images-amazon.com/images/I/913MEWzd9gL._SL1500_.jpg',
  },
  {
    week: '051720',
    headline: 'Blinding Lights',
    citation: 'The Weeknd',
    link: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ',
    img: 'https://i.ytimg.com/vi/J7p4bzqLvCw/maxresdefault.jpg',
  },
  {
    week: '052420',
    headline: 'Watermelon Sugar',
    citation: 'Harry Styles',
    link: 'https://www.youtube.com/watch?v=E07s5ZYygMg',
    img:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTw494SVhZVMQwM945nArO2Uzrd1nRIiHWqPgQvbW9Yhn7ROH2l&usqp=CAU',
  },
  {
    week: '053120',
    headline: 'Broken People',
    citation: "Logic & Rag'n'Bone",
    link: 'https://www.youtube.com/watch?v=o9zRQijCN5w',
    img: 'https://static.hiphopdx.com/2017/11/Logic1-826x620.jpg',
  },
  {
    week: '060720',
    headline: 'Glory',
    citation: 'John Legend & Common',
    link: 'https://www.youtube.com/watch?v=HUZOKvYcx_o',
    img: 'https://mtv.mtvnimages.com/uri/mgid:ao:image:mtv.com:67857?quality=0.8&format=jpg&width=1440&height=810&.jpg',
  },
  {
    week: '061420',
    headline: 'You Should be Sad',
    citation: 'Halsey',
    link: 'https://www.youtube.com/watch?v=8nBFqZppIF0',
    img: 'https://img.particlenews.com/image.php?type=thumbnail_1024x576&url=0nXrft_0NoHharO00',
  },
  {
    week: '062120',
    headline: 'RITMO',
    citation: 'Black Eyed Peas',
    link: 'https://www.youtube.com/watch?v=EzKkl64rRbM',
    img: 'https://jmgmags.com/wp-content/uploads/2019/10/blackeyedpeas.jpg',
  },
  {
    week: '062820',
    headline: 'The Bones',
    citation: 'Maren Morris',
    link: 'https://www.youtube.com/watch?v=gvPMVKUI9go',
    img: 'https://i.ytimg.com/vi/Zmxfd3Z_wBA/maxresdefault.jpg',
  },
  {
    week: '070520',
    headline: 'Before You Go',
    citation: 'Lewis Capaldi',
    link: 'https://www.youtube.com/watch?v=Jtauh8GcxBY',
    img: 'https://all-noise.co.uk/wp-content/uploads/2019/05/lewis-capaldi.jpg',
  },
  {
    week: '071220',
    headline: 'Dream Girl',
    citation: 'Anna of the North',
    link: 'https://www.youtube.com/watch?v=3b0HXEymmSI',
    img: 'https://i.ytimg.com/vi/Ix09qwHH0m8/maxresdefault.jpg',
  },
  {
    week: '071920',
    headline: 'Get Back Up',
    citation: 'G-Eazy',
    link: 'https://www.youtube.com/watch?v=J-_tv7Y0DAo',
    img: 'https://dslv9ilpbe7p1.cloudfront.net/BL47nZQCoTvWtf5THebEbA_store_header_image',
  },
  {
    week: '072620',
    headline: 'Be Like That',
    citation: 'Kane Brown, Swae Lee, & Khalid',
    link: 'https://www.youtube.com/watch?v=QeW3iUbc6S0&list=RDCLAK5uy_lBNUteBRencHzKelu5iDHwLF6mYqjL-JU&index=2',
    img:
      'https://secureservercdn.net/198.71.233.109/c8l.77c.myftpupload.com/wp-content/uploads/2020/07/kanebrownthat.jpeg?time=1595055227',
  },
  {
    week: '080220',
    headline: 'Feel You',
    citation: 'My Morning Jacket',
    link: 'https://www.youtube.com/watch?v=WFl0Kotmj7U',
    img: 'https://lightning100.com/wp-content/uploads/My-Morning-Jacket.jpg',
  },
  {
    week: '080920',
    headline: 'Future Islands',
    citation: 'For Sure',
    link: 'https://www.youtube.com/watch?v=yC_2tlsnpMw',
    img:
      'https://i1.wp.com/www.xsnoize.com/wp-content/uploads/2020/07/0675a1fa-1888-4f6e-b8a4-3b6a0bfd3e74.jpg?resize=678%2C381&ssl=1',
  },
  {
    week: '081620',
    headline: 'Hell N Back',
    citation: 'Bakar',
    link: 'https://www.youtube.com/watch?v=BdrNvQ4YCng',
    img: 'https://i1.wp.com/coolhunting.com/wp-content/uploads/2019/08/bakar.jpg?fit=700%2C700&ssl=1&w=640',
  },
  {
    week: '082320',
    headline: 'No Glory in the West',
    citation: 'Orville Peck',
    link: 'https://www.youtube.com/watch?v=TU0TAsEjUpg',
    img: 'https://etcanada.com/wp-content/uploads/2020/05/Peck.jpg?quality=80&strip=all',
  },
  {
    week: '083020',
    headline: 'My Rajneesh',
    citation: 'Sufjan Stevens',
    link: 'https://www.youtube.com/watch?v=jn7_JpmhZP0',
    img: 'https://i.ytimg.com/vi/jn7_JpmhZP0/maxresdefault.jpg',
  },
  {
    week: '090620',
    headline: 'Under the Thunder',
    citation: 'Skeggs',
    link: 'https://www.youtube.com/watch?v=R424TyjWWJk',
    img: 'https://tonedeaf.thebrag.com/wp-content/uploads/2019/10/Skegss.jpg',
  },
  {
    week: '091320',
    headline: 'My Silver Lining',
    citation: 'First Aid Kit',
    link: 'https://www.youtube.com/watch?v=sNNYtm2XJGc',
    img:
      'https://img.discogs.com/2C2uKIDM1t0Vj-ieYqVO_cfUALs=/fit-in/598x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6077203-1410460426-8287.jpeg.jpg',
  },
  {
    week: '092020',
    headline: "Roboto's Outro",
    citation: 'PPK',
    link: 'https://www.youtube.com/watch?v=2OKU4ohLpJI',
    img: 'https://images-na.ssl-images-amazon.com/images/I/51sixkO2vZL._SX342_QL70_ML2_.jpg',
  },
  {
    week: '092720',
    headline: 'Midnight Sky',
    citation: 'Miley Cyrus',
    link: 'https://www.youtube.com/watch?v=aS1no1myeTM',
    img:
      'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2020%2F08%2F06%2FMidnight-Sky.jpg&q=85',
  },
  {
    week: '100420',
    headline: 'Mood',
    citation: '24kGoldn',
    link: 'https://www.youtube.com/watch?v=GrAchTdepsU',
    img:
      'https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_90,w_1400/fl_lossy,pg_1/mcsyut9bqalqusyxpwjd/24kgold-mood',
  },
  {
    week: '101120',
    headline: 'Choice is Yours',
    citation: 'Stick Figure',
    link: 'https://www.youtube.com/watch?v=xV-lMtisZw0',
    img: 'https://c.saavncdn.com/158/Choice-is-Yours-feat-Slightly-Stoopid-English-2015-500x500.jpg',
  },
  {
    week: '101820',
    headline: 'Dreams',
    citation: 'Fleetwood Mac',
    link: 'https://www.youtube.com/watch?v=mrZRURcb1cM',
    img: 'https://d.newsweek.com/en/full/879297/43-fleetwood-mac-rumours.webp?w=790&f=2583ce7fc1879a28c6ad170cfa22e66e',
  },
  {
    week: '102520',
    headline: 'Giants',
    citation: 'Dermot Kennedy',
    link: 'https://www.youtube.com/watch?v=Fi33qkv4Bjw',
    img: 'https://d3bzyjrsc4233l.cloudfront.net/news/Giants.png',
  },
  {
    week: '110120',
    headline: 'Marigolds',
    citation: 'Early Eyes',
    link: 'https://www.youtube.com/watch?v=bRy7AQOFB-k',
    img: 'https://images.genius.com/c1be8d57b6210a924d66d8e96860cb41.400x400x1.png',
  },
  {
    week: '110820',
    headline: 'My Name is Dark',
    citation: 'Grimes',
    link: 'https://www.youtube.com/watch?v=xTzUVCwFacs',
    img: 'https://m.media-amazon.com/images/I/811QLHsHGnL._SS500_.jpg',
  },
  {
    week: '111520',
    headline: 'Good Bad Times',
    citation: 'Hind',
    link: 'https://www.youtube.com/watch?v=XVdJUy5KCJY',
    img: 'https://static.stereogum.com/uploads/2020/02/Hinds-The-Prettiest-Curse-Album-Art-1-1580772038-640x640.png',
  },
  {
    week: '112220',
    headline: 'Imagination',
    citation: 'Foster the People',
    link: 'https://www.youtube.com/watch?v=4C7EGz5EwYE',
    img: 'https://images.genius.com/2ccd52010d803c7a251b54544ce25f01.1000x1000x1.jpg',
  },
  {
    week: '112920',
    headline: 'Dakiti',
    citation: 'Bad Bunny',
    link: 'https://www.youtube.com/watch?v=TmKh7lAwnBI',
    img: 'https://elgenero.com/images/subir/images/1604030647www.jpg',
  },
  {
    week: '120620',
    headline: 'Some Feeling',
    citation: 'Mild Orange',
    link: 'https://www.youtube.com/watch?v=6I44IYGyB_4',
    img: 'https://i1.sndcdn.com/artworks-000341955555-67i1p5-t500x500.jpg',
  },
  {
    week: '121320',
    headline: 'Home',
    citation: 'Solomun',
    link: 'https://www.youtube.com/watch?v=5Fc9A6mLHJU',
    img: 'https://i0.wp.com/electronicgroove.com/wp-content/uploads/2018/11/Solomun-1.jpg',
  },
  {
    week: '122020',
    headline: 'Under the Pressure',
    citation: 'The War on Drugs',
    link: 'https://www.youtube.com/watch?v=vkLOg252KRE',
    img: 'https://i.ytimg.com/vi/Y5DzTaYakLo/maxresdefault.jpg',
  },
  {
    week: '122720',
    headline: 'Stay Alive',
    citation: 'Jose Gonzalez',
    link: 'https://www.youtube.com/watch?v=_HWRGKfSq3A',
    img: 'https://i.ytimg.com/vi/bvjNyJ8TBNk/maxresdefault.jpg',
  },
  {
    week: '010321',
    headline: 'SONG',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1458560871784-56d23406c091?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80',
  },
];
