let websitesData = [
  {
    week: '042620',
    headline: 'Webcomic Extraordinaire',
    citation: 'xkcd.com',
    link: 'https://xkcd.com/',
    img: 'https://imgs.xkcd.com/comics/fresh_pears.png',
  },
  {
    week: '050320',
    headline: 'COVID-19 Visualizer',
    citation: 'Johns Hopkins',
    link: 'https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6',
    img: 'https://www.wjhl.com/wp-content/uploads/sites/98/2020/03/johns.jpg?w=1871&h=939&crop=1',
  },
  {
    week: '051020',
    headline: 'Meditation Sounds',
    citation: 'MyNoise.net',
    link: 'https://mynoise.net/NoiseMachines/tibetSoundscapeGenerator.php',
    img: 'https://mynoise.net/Data/TIBET/fb.jpg',
  },
  {
    week: '051720',
    headline: 'Free Photos for Everyone',
    citation: 'Unsplash',
    link: 'https://unsplash.com/',
    img:
      'https://images.unsplash.com/photo-1589571853022-d99bb65a2391?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80',
  },
  {
    week: '052420',
    headline: 'Interactive Generative Art',
    citation: 'Weave Silk',
    link: 'http://weavesilk.com/',
    img:
      'https://d2.alternativeto.net/dist/s/weavesilk-com_749978_full.png?format=jpg&width=1600&height=1600&mode=min&upscale=false',
  },
  {
    week: '053120',
    headline: 'Make your writing bold and clear',
    citation: 'Hemingway Editor',
    link: 'http://www.hemingwayapp.com/',
    img: 'https://blog.dundee.ac.uk/web/files/2017/10/Screen-Shot-2017-10-19-at-10.56.19-1024x697.png',
  },
  {
    week: '060720',
    headline: 'Learn from the Experts',
    citation: 'The Big Think',
    link: 'https://bigthink.com/',
    img: 'https://i.ytimg.com/vi/7QLks9QkVLM/maxresdefault.jpg',
  },
  {
    week: '061420',
    headline: 'Know your Body, Simplify Your Workouts',
    citation: 'MuscleWiki',
    link: 'https://musclewiki.org/',
    img: 'https://d2.alternativeto.net/dist/s/musclewiki_249244_full.png?format=jpg&width=1200&height=1200&mode=crop',
  },
  {
    week: '062120',
    headline: 'Discover the best sources for any topic',
    citation: 'Feedly',
    link: 'https://feedly.com/i/discover',
    img: 'https://s5.feedly.com/images/fx/landing/source-browser-full-v2@2x.png',
  },
  {
    week: '062820',
    headline: 'Bring Emojis to life',
    citation: 'Stinkmoji',
    link: 'https://stinkmoji.cool/',
    img: 'https://stinkmoji.cool/share/share_twitter.png',
  },
  {
    week: '070520',
    headline: 'Create interactive designs and graphics',
    citation: 'Google Designer',
    link: 'https://webdesigner.withgoogle.com/',
    img: 'https://www.elegantthemes.com/blog/wp-content/uploads/2018/06/template-gallery.png',
  },
  {
    week: '071220',
    headline: 'Discover obscure Spotify songs',
    citation: 'Forgotify',
    link: 'http://forgotify.com/',
    img: 'https://static.billboard.com/files/media/spotify-july-2018-billboard-1548-1024x677.jpg',
  },
  {
    week: '071920',
    headline: 'Amazing free design tool',
    citation: 'Figma',
    link: 'https://www.figma.com/',
    img: 'https://miro.medium.com/max/5236/1*4clb6MHlPKalAA1jDy-ahA.jpeg',
  },
  {
    week: '072620',
    headline: 'Organize team projects remotely',
    citation: 'Asana',
    link: 'https://www.asana.com/',
    img: 'https://miro.medium.com/max/2400/1*2DRJYDBh8C5HpXTx9X8pHg.png',
  },
  {
    week: '080220',
    headline: 'Find youtube videos based on Geo Location',
    citation: 'Geonarra',
    link: 'https://www.geonarra.com/',
    img:
      'https://i0.wp.com/geoawesomeness.com/wp-content/uploads/2016/03/Geo-search-youtube-tool-Geoawesomeness.png?fit=890%2C453&ssl=1',
  },
  {
    week: '080920',
    headline: 'Wind & Weather Patterns',
    citation: 'Windy',
    link: 'https://www.windy.com/',
    img: 'https://farm5.staticflickr.com/4787/40732725772_9fe2983966_b.jpg',
  },
  {
    week: '081620',
    headline: 'Online Card Table',
    citation: 'PlayingCards.io',
    link: 'http://playingcards.io/game/standard-deck',
    img: 'https://cdn.24.co.za/files/Cms/General/d/5595/1b9e332743a44ea79bc69d1521af7353.jpg',
  },
  {
    week: '082320',
    headline: 'This Day in History',
    citation: 'On This Day',
    link: 'https://www.onthisday.com/',
    img: 'https://roodepoortrecord.co.za/wp-content/uploads/sites/20/2016/07/Onthisdaydayin_85450.jpg',
  },
  {
    week: '083020',
    headline: 'Cool Gadets and Gear',
    citation: 'Uncrate',
    link: 'https://uncrate.com/',
    img: 'https://i0.wp.com/digiday.com/wp-content/uploads/2013/08/uncrate.jpg?fit=1048%2C525&ssl=1',
  },
  {
    week: '090620',
    headline: 'See the night sky in your area',
    citation: 'Stellarium',
    link: 'https://stellarium-web.org/',
    img:
      'https://img.buzzfeed.com/buzzfeed-static/static/2020-03/18/21/asset/deea4d0073df/sub-buzz-208-1584565688-8.png?downsize=600:*&output-format=auto&output-quality=auto',
  },
  {
    week: '091320',
    headline: 'An addictive game',
    citation: '2048',
    link: 'https://play2048.co/',
    img: 'https://sourcedigit.com/wp-content/uploads/2014/03/2048-Game1.png',
  },
  {
    week: '092020',
    headline: 'A never ending beautiful animation',
    citation: 'Zoom Quilt',
    link: 'https://zoomquilt.org/',
    img: 'https://i.ytimg.com/vi/INqKqk-ifpc/maxresdefault.jpg',
  },
  {
    week: '092720',
    headline: 'Guess where you are by a picture',
    citation: 'Geo Guesser',
    link: 'https://www.geoguessr.com/',
    img: 'https://img2.thejournal.ie/inline/2008293/original/?width=630&version=2008293',
  },
  {
    week: '100420',
    headline: 'Play the wikipedia game',
    citation: 'Wiki Game',
    link: 'https://www.thewikigame.com/',
    img: 'https://img2.thejournal.ie/inline/2008359/original/?width=630&version=2008359',
  },
  {
    week: '101120',
    headline: 'Discover similar bands',
    citation: 'Music Map',
    link: 'https://www.music-map.com/',
    img: 'https://img2.thejournal.ie/inline/2008376/original/?width=630&version=2008376',
  },
  {
    week: '101820',
    headline: 'Geography Quizzes',
    citation: 'LizardPoint',
    link: 'https://lizardpoint.com/geography/index.php',
    img: 'https://lizardpoint.com/images/geography-screenshot-800.gif',
  },
  {
    week: '102520',
    headline: 'Play the classic game',
    citation: 'The Oregon Trail',
    link: 'https://archive.org/details/msdos_Oregon_Trail_Deluxe_The_1992',
    img:
      'https://classicreload.com/sites/default/files/styles/game_image/public/the-oregon-trail-deluxe.png?itok=SkSCXJWF',
  },
  {
    week: '110120',
    headline: 'Best Recipe Website',
    citation: 'Serious Eats',
    link: 'https://www.seriouseats.com/',
    img: 'https://static.seriouseats.com/1/braestar/live/img/og-image-q4-turkey.jpg',
  },
  {
    week: '110820',
    headline: 'WEBSITE',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '111520',
    headline: 'WEBSITE',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '112220',
    headline: 'WEBSITE',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '112920',
    headline: 'WEBSITE',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '120620',
    headline: 'WEBSITE',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '121320',
    headline: 'WEBSITE',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '122020',
    headline: 'WEBSITE',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '122720',
    headline: 'WEBSITE',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
  {
    week: '010321',
    headline: 'WEBSITE',
    citation: 'Citation',
    link: '#',
    img:
      'https://images.unsplash.com/photo-1530435460869-d13625c69bbf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
  },
];
